on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
name: CI
jobs:
  formatted:
    name: Formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: |
          just fmt
          git diff
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - name: Run tests
        run: just test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOPROXY: direct
    steps:
      - uses: actions/checkout@v4
      - uses: cashapp/activate-hermit@v1
      - run: just lint
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: ["test", "lint"]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cashapp/activate-hermit@v1
      - run: goreleaser release --fail-fast
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
